config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  get 'help' => 'home#help'
  get 'about' => 'home#about'
  get 'contact' => 'home#contact'
  resources :sessions, only: [:new, :create, :destroy]
  get 'signup' => "users#new"
  get    'signin'   => 'sessions#new'
  delete 'signout'  => 'sessions#destroy'
  resources :users, except: [:destroy, :index]
  resources :medias, only: [:create, :destroy]

end

app/models/media.rb
class Media < ActiveRecord::Base
  validates :user_id, presence: true
  belongs_to :user
  PERMISSION_HASH =  {is_private: 0, is_public: 1}.freeze
  validates :permission, :inclusion => {:in =>[PERMISSION_HASH[:is_private], PERMISSION_HASH[:is_public]]}
  validates :description, presence: true, length: { maximum: 255}

  VALID_URL_REGEX = /\A(http|https):\/\/[a-z0-9]+([\-\.]{1}[a-z0-9]+)*\.[a-z]{2,5}(:[0-9]{1,5})?(\/.*)?\z/ix

  validates :url, presence: true,
            format: { with: VALID_URL_REGEX, message: "Invalid url. A valid url format is: http(s)://www.example.com" }

  # Fetches public media
  def self.public_media(keyword='')
    where("LOWER(description) LIKE LOWER(?) AND permission = ?", "%#{keyword}%", Media::PERMISSION_HASH[:is_public]).order("id DESC")
  end


end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :medias, -> { order "created_at DESC" }, dependent: :destroy
  before_save {email.downcase!}
  before_create :create_remember_token

  validates :first_name, presence: true, length: { maximum: 50}
  validates :last_name, presence: true, length: { maximum: 50}

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/i

  validates :email, presence: true, format: { with: VALID_EMAIL_REGEX },
            uniqueness: { case_sensitive: false }

  validates :password, presence: true, length: { minimum: 6}

  has_secure_password

  def name
    first_name + ' ' + last_name
  end

  def User.new_remember_token
    SecureRandom.urlsafe_base64
  end

  def User.encrypt(token)
    Digest::SHA1.hexdigest(token.to_s)
  end

  def feed(keyword = '')
    self.medias.where('LOWER(description) LIKE LOWER(?)', "%#{keyword}%")
  end

  private

    def create_remember_token
      self.remember_token = User.encrypt(User.new_remember_token)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    if signed_in?
      redirect_to user_path(current_user)
    else
      params[:q] ||= '%'
      @public_media = Media.public_media(params[:q]).paginate(:page => params[:page], :per_page => 30)
    end
  end

  def help
  end

  def about
  end

  def contact
  end
end

app/controllers/media_controller.rb
class MediaController < ApplicationController
  before_action :signed_in_user
  before_action :correct_user, only: :destroy

  def create
    @media = current_user.media.build(description: media_params[:description],
                                      url: media_params[:url], permission: media_params[:permission])
    if @media.save
      flash[:success] = "Media created!"
      redirect_to root_url
    else
      render root_url
    end

  end

  def destroy
    @media.destroy
    redirect_to root_url
  end


  private
    def media_params
      params.require(:media).permit(:description, :permission, :url)
    end

    def correct_user
      @media = current_user.medias.find_by(id: params[:id])
      redirect_to root_url if @media.nil?
    end
end

app/controllers/medias_controller.rb
class MediasController < ApplicationController
  before_action :signed_in_user
  before_action :correct_user, only: :destroy

  def create
    @media = current_user.medias.build(description: media_params[:description],
                                      url: media_params[:url], permission: media_params[:permission].to_i)
    if @media.save
      flash[:success] = "Media created!"
    else
      flash[:error] = @media.errors.full_messages.join(',  ')
    end
    redirect_to root_url

  end

  def destroy
    @media.destroy
    redirect_to root_url
  end


  private
    def media_params
      params.require(:media).permit(:description, :permission, :url)
    end

    def correct_user
      @media = current_user.medias.find_by(id: params[:id])
      redirect_to root_url if @media.nil?
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
    redirect_to root_path if current_user.present?
  end

  def create
    user = User.find_by(email: session_params[:email])
    if user && user.authenticate(session_params[:password])
      sign_in user
      redirect_back_or user
    else
      flash.now[:error] = "Invalid email/password combination."
      render 'new'
    end
  end

  def destroy
    sign_out
    redirect_to root_url
  end

  private

    def session_params
      params.permit(:email, :password)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :signed_in_user, only: [:edit, :update, :destroy]
  before_action :correct_user, only: [:edit, :update, :show]
  before_action :is_signed_in, only: [:new, :create]

  def show
    @user = User.find_by(id: params[:id])
    @new_media = current_user.medias.build
    params[:q] ||= '%'
    @media_permissions = Media::PERMISSION_HASH
    @medias = @user.feed(params[:q]).paginate(:page => params[:page], :per_page => 30)
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      sign_in @user
      flash[:success] = "Welcome to the Media Community!"
      redirect_to @user
    else
      render 'new'
    end
  end

  def edit

  end

  def update
    if @user.update_attributes(user_params)
      flash[:success] = "Profile updated"
      sign_in @user
      redirect_to @user
    else
      render 'edit'
    end
  end


  private
    def user_params
      params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation)
    end
    # Before filters

    def correct_user
      @user = User.find_by(id: params[:id]) # rescue nil, just in case there is no user with params[:id]
      redirect_to(root_url) unless current_user?(@user)
    end

    def is_signed_in
      redirect_to(root_url) if signed_in?
    end
end

app/helpers/application_helper.rb
module ApplicationHelper

  # Returns full title on a per-page basis
  def full_title(page_title)
    base_title = "Media Application"
    if page_title.blank?
      base_title
    else
      "#{base_title} | #{page_title}"
    end
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/media_helper.rb
module MediaHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

  def sign_in(user)
    remember_token = User.new_remember_token
    cookies.permanent[:remember_token] = remember_token
    user.update_attribute(:remember_token, User.encrypt(remember_token))
    self.current_user = user
  end

  def current_user=(user)
    @current_user = user
  end

  def current_user
    remember_token = User.encrypt(cookies[:remember_token])
    @current_user ||= User.find_by(remember_token: remember_token)
  end

  def signed_in?
    !current_user.nil?
  end

  def sign_out
    self.current_user = nil
    cookies.delete(:remember_token)
  end

  def current_user?(user)
    current_user == user
  end

  def store_location
    session[:return_to] = request.url if request.get?
  end

  def redirect_back_or(default)
    redirect_to(session[:return_to] || default)
    session.delete(:return_to)
  end

  def signed_in_user
    unless signed_in?
      store_location
      redirect_to signin_url, notice: "Please sign in."
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper

  # Returns the Gravatar (http://gravatar.com/) for the given user
  def gravatar_for(user, options={size: 50})
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?size=#{size}"
    image_tag(gravatar_url, alt: user.first_name, class: 'gravatar')
  end
end

app/views/home/about.html.erb
<h1>About Page</h1>

app/views/home/contact.html.erb
<h1>Contact Me:</h1>
<address>
  Written by <a href="mailto:chandan.jhun@gmail.com">Chandan Kumar</a>.<br>
  Visit my blog <a href="http://indyarock.wordpress.com" target="_blank">here</a><br>
</address>

app/views/home/help.html.erb
<h1>Help Page</h1>

app/views/home/index.html.erb
<% provide(:title, "Home Page") %>
<div class="searchBar">
  <form action="/" method="GET">
    Search: <input type="text" name="q" style="width: 200px;" />
  </form>
</div>
<ul class="mediaList">
  <% @public_media.each do |media| %>
      <%
         img_url = media[:url].include?("youtube") ? 'http://gadgetbox.com.br/Mercadolivre/Anuncios/Peliculas_de_Vidro_Nillkin/Imagens/youtube-logo-play-button.png' : media[:url]
      %>
      <li class="mediaItem">
        <div class="imgWrap">
          <a href="<%= media[:url] %>" target="_blank">
            <img alt='Public Media' src="<%= img_url %>"/>
          </a>
        </div>
        <div class="descWrap">
          <%= link_to media[:description], media[:url], target: '_blank' %>
        </div>
        <span class="timestamp">
                Posted <%= time_ago_in_words(media.created_at) %> ago.
            </span>
        <div class="clear"></div>
      </li>
  <% end %>
</ul>
<%= will_paginate(@public_media) %>

app/views/layouts/_footer.html.erb
<footer class="footer">
        <small>
          Developed
    by Chandan Kumar
  </small>
<nav>
<ul>
    <li><%= link_to 'About', about_path %></li>
    <li><%= link_to 'Contact', contact_path %></li>
</ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="navbar-inner">
    <div class="container">
      <%= link_to 'Media Application', root_path, id: "logo" %>
      <nav>
        <ul class="nav pull-right">
          <li><%= link_to 'Home', root_path %></li>
          <li><%= link_to 'Help', help_path %></li>
          <% if current_user %>
              <li id="fat-menu" class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                  Account <b class="caret"></b>
                </a>
                <ul class="dropdown-menu">
                  <li><%= link_to "Settings", edit_user_path(current_user) %></li>
                  <li class="divider"></li>
                  <li>
                    <%= link_to "Sign out", signout_path, method: 'delete' %>
                  </li>
                </ul>
              </li>
          <% else %>
              <li><%= link_to 'Sign In', signin_path %></li>
          <% end %>
        </ul>
      </nav>
    </div>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title(yield(:title)) %></title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= render 'layouts/header' %>
<div class="container">
  <% flash.each do |key, value| %>
      <%= content_tag(:div, value, class: "alert alert-#{key}")%>
  <% end %>

  <%= yield %>

</div>
<div class="container">
  <%= render 'layouts/footer' %>
</div>
</body>
</html>

app/views/media/_media.html.erb
<li>
  <%= link_to "#{media.description}", "#{media.url}" , class: "content"%>
  <span class="timestamp">
    Posted <%= time_ago_in_words(media.created_at) %> ago.
  </span>
  <% if current_user?(media.user) %>
    <%= link_to "delete", media, method: :delete,
                                          data: { confirm: "Are you sure?"},
                                          title: media.description %>
  <% end %>
</li>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
    <div id="error_explanation">
      <div class="alert alert-error">
        The form contains <%= pluralize(object.errors.count, "error") %>
      </div>
      <ul>
        <% object.errors.full_messages.each do |msg| %>
        <li>* <%= msg %></li>
        <% end %>
      </ul>
    </div>
<% end %>

app/views/shared/_media_form.html.erb
<%= form_for(@new_media) do |f| %>
    <%= render 'shared/error_messages', object: f.object %>

    <div class="field">
      <%= f.text_area :description , placeholder: "Compose new media..." %>
    </div>
    <div class="field">
      <%= f.text_field :url , placeholder: "Youtube or Image link" %>
    </div>
    Mark it Public: <%= check_box('media', 'permission') %></br>

    <%= f.submit "Post", class: "btn btn-large btn-primary" %>

<% end %>

app/views/shared/_medias.html.erb
<% if @medias.any? %>
    <ol class="medias">
      <% @medias.each do |media| %>
          <% public_media =  (@media_permissions[:is_public] == media.permission) %>
          <li id="<%= media.id %>" class="<%= 'public-media' if public_media %>">
            <div>
            <span class="content">
              <% if public_media %>
                  <%= image_tag('public.png', size: "20x20", alt: "Public", title: 'Public Media')%>
              <% end %>
              <%= link_to "#{media.description}", "#{media.url}", :target => "_blank" %>
            </span>
            </div>
            <span class="timestamp">
                Posted <%= time_ago_in_words(media.created_at) %> ago.
            </span>
            <%= link_to "delete", media, method: :delete,
                        data: { confirm: "Are you sure?"} %>
          </li>
      <% end %>
    </ol>
    <%= will_paginate @medias %>
<% end %>

app/views/users/_fields.html.erb
<%= render 'shared/error_messages', object: f.object %>

<%= f.label :first_name %>
<%= f.text_field :first_name %>

<%= f.label :last_name %>
<%= f.text_field :last_name %>

<%= f.label :email %>
<%= f.text_field :email %>

<%= f.label :password %>
<%= f.password_field :password %>

<%= f.label :password_confirmation, "Confirm Password" %>
<%= f.password_field :password_confirmation %>

app/views/users/edit.html.erb
<% provide(:title, "Edit user") %>
<h1>Update your profile</h1>
<div class="row">
  <div class="span6 offset3">
    <%= form_for(@user) do |f| %>

        <%= render 'fields', f: f %>

        <%= f.submit "Save changes", class: "btn btn-large btn-primary" %>
    <% end %>

    <%= gravatar_for @user %>
    <%= link_to "Change", "http://gravatar.com/emails", target: "_blank" %>
  </div>
</div>

app/views/users/new.html.erb
<%= provide(:title, 'Sign Up') %>
<h1>Sign Up</h1>
<div class="row">
  <div class="span6 offset3">
    <%= form_for(@user) do |f| %>

        <%= render 'fields', f: f %>

        <%= f.submit "Create my account", class: "btn btn-large btn-primary" %>

    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<%= provide(:title, @user.first_name) %>
<div class="row">
  <aside class="span4">
    <section>
      <h1>
        <%= gravatar_for @user %>
        <%= "#{@user.first_name} #{@user.last_name}"%>
      </h1>
    </section>
    <section>
      <%= render 'shared/media_form', locals: {media: @new_media} %>
    </section>
    <span> Total Posts:
    <%= pluralize(current_user.medias.count, "media") %>
    </span>
  </aside>
  <div class="searchBar">
    <form action="<%= user_path(@user) %>" method="GET">
      Search Post: <input type="text" name="q" style="width: 200px;" />
    </form>
  </div>
  <div class="span8">
    <% if @user.medias.any? %>
        <ol class="media">
          <%= render 'shared/medias', locals: {medias: @medias, media_permissions: @media_permissions} %>
        </ol>
        <%= will_paginate(@medias) %>
    <% end %>
  </div>
</div>